services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./internal/grafana/loki/local-config.yml:/etc/loki/local-config.yml
      - ${LOCAL_LOKI_DIR}:/loki
    networks:
      - loki-network
    env_file: 
      - path: ./.env
        required: true

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./internal/grafana/promtail/config.yml:/etc/promtail/config.yml
      - ${LOG_PATH}:/var/log/raspberry_sensors
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network
    env_file: 
      - path: ./.env
        required: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - loki-network

volumes:
  grafana-storage:

networks:
  loki-network:
    driver: bridge