api:
  host: "localhost"
  port: 8080

database:
  host: localhost
  port: 8086
  token: <your inglux DB token>

logger:
  path: "log.log"
  # zerolog levels are 'trace', 'debug', 'info', 'warn', 'error', 'fatal' and 'panic'
  level: "info"