{
 "title": "BME280 daily aggregations",
 "time": { "from": "2024-09-09T22:00:00.000Z", "to": "2024-09-11T22:00:00.000Z" },
 "panels": [
  {
   "title": "BME280 daily average",
   "type": "timeseries",
   "description": "Temperature, pressure and humidity. Points are averaged over one day.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_mean\" or r._field == \"pressure_hpa_mean\" or r._field == \"humidity_percent_mean\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_mean\", \"pressure_hpa_mean\", \"humidity_percent_mean\"])\n"
    }
   ]
  },
  {
   "title": "BME280 daily average temperature distribution",
   "type": "histogram",
   "description": "Average values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_mean\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_mean\"])"
    }
   ]
  },
  {
   "title": "BME280 daily average pressure distribution",
   "type": "histogram",
   "description": "Average values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"pressure_hpa_mean\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"pressure_hpa_mean\"])"
    }
   ]
  },
  {
   "title": "BME280 daily average humidity distribution",
   "type": "histogram",
   "description": "Average values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"humidity_percent_mean\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"humidity_percent_mean\"])"
    }
   ]
  },
  {
   "title": "BME280 daily median temperature distribution",
   "type": "histogram",
   "description": "Median values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_median\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_median\"])"
    }
   ]
  },
  {
   "title": "BME280 daily median pressure distribution",
   "type": "histogram",
   "description": "Median values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"pressure_hpa_median\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"pressure_hpa_median\"])"
    }
   ]
  },
  {
   "title": "BME280 daily median humidity distribution",
   "type": "histogram",
   "description": "Median values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"humidity_percent_median\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"humidity_percent_median\"])"
    }
   ]
  },
  {
   "title": "BME280 daily median",
   "type": "timeseries",
   "description": "Temperature, pressure and humidity. Median values are computed over one day.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_median\" or r._field == \"pressure_hpa_median\" or r._field == \"humidity_percent_median\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_median\", \"pressure_hpa_median\", \"humidity_percent_median\"])"
    }
   ]
  },
  {
   "title": "BME280 daily stddev temperature distribution",
   "type": "histogram",
   "description": "Stddev values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_stddev\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_stddev\"])"
    }
   ]
  },
  {
   "title": "BME280 daily stddev pressure distribution",
   "type": "histogram",
   "description": "Stddev values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"pressure_hpa_stddev\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"pressure_hpa_stddev\"])"
    }
   ]
  },
  {
   "title": "BME280 daily stddev",
   "type": "histogram",
   "description": "Stddev values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"humidity_percent_stddev\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"humidity_percent_stddev\"])"
    }
   ]
  },
  {
   "title": "BME280 daily standard deviation",
   "type": "timeseries",
   "description": "Temperature, pressure and humidity. Standard deviation values are computed over one day.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_stddev\" or r._field == \"pressure_hpa_stddev\" or r._field == \"humidity_percent_stddev\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_stddev\", \"pressure_hpa_stddev\", \"humidity_percent_stddev\"])"
    }
   ]
  },
  {
   "title": "BME280 daily extrema temperature distribution",
   "type": "histogram",
   "description": "Values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"temperature_celsius_max\" or r._field == \"temperature_celsius_min\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"temperature_celsius_max\", \"temperature_celsius_min\"])"
    }
   ]
  },
  {
   "title": "BME280 daily extrema pressure distribution",
   "type": "histogram",
   "description": "Values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"pressure_hpa_max\" or r._field == \"pressure_hpa_min\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"pressure_hpa_max\", \"pressure_hpa_min\"])"
    }
   ]
  },
  {
   "title": "BME280 daily extrema humidity distribution",
   "type": "histogram",
   "description": "Values are computed over one day.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"daily\")\n  |> range(start: 1970-01-01T00:00:00Z, stop: date.add(d: 2d, to: today()))\n  |> filter(fn: (r) => r._measurement == \"environment_bme280\")\n  |> filter(fn: (r) => r._field == \"humidity_percent_max\" or r._field == \"humidity_percent_min\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"humidity_percent_max\", \"humidity_percent_min\"])"
    }
   ]
  }
 ]
}