{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"raspberry-pi-logs\"} | json | line_format \"{{ .time }} {{ .level }} {{ .caller }}: {{ .message }}\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"raspberry-pi-logs\"} | json | level = `error` | line_format `{{ .time }} {{ .level }} {{ .caller }}: {{ .message }}`"
    }
   ]
  },
  {
   "title": "All but debug logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"raspberry-pi-logs\"} | json | level != `debug` | line_format `{{ .time }} {{ .level }} {{ .caller }}: {{ .message }}`"
    }
   ]
  }
 ]
}